### ISSUE TITLE
Any chance this could be adapted in the same manner? Virginia Dominion Energy

### ISSUE THREAD

**Issue by Imburr** [alphasixtyfive/HomeAssistantConfigs#1]
https://utilityapi.com/docs/utilities/dominion

If possible I might hire a developer to develop it, it is beyond my ability.

**Comment by alphasixtyfive** [comment]
It might be but I don't even see API endpoints as one would need a password to access it. Please also note that why I did was clearly not the right way of doing it but I wanted to see if I could get away without using any custom components.

**Comment by Imburr** [comment]
10-4, thanks!
